### ISSUE TITLE
LMS not starting to play

### ISSUE THREAD

**Issue by ekkesa** [ynot123/LMS_Controls#1]
Hi,
Firstly thank you for an awesome integration. Unfortunately I cant get it up and running.

I see these errors in my HA logs:

 Error rendering data template: UndefinedError: 'queryResult' is undefined

Google Assistant is responding 100% but LMS is not triggered. Any suggestions?

**Comment by ynot123** [comment]
Sounds like your fulfillment (JSON) is not being received by HA from DialogFlow, in the fullfilment section ensure:
- webhook is enabled
the URL reads something like:  https://YourHALink.duckdns.org/api/services/script/lms_control?api_password=YourAPIPassword 
  
Also try the GUI version (doesn't need voice) and test the functions to see if the HA part is working properly.

**Comment by ekkesa** [comment]
Thx! I double checked the fulfillment URL and it is definitely there. I can test the agent on DF web interface. It replies with all the correct answers, but nothing happens on LMS. From the HA interface I can use the local source (lms) to play music, but not spotify (believe you need a premium account for it to work)

**Comment by ynot123** [comment]
I will put together a troubleshooting file in the near future to help with these issues.  That being said:
- Sounds like the HA part is working.  I assume you can play, pause, shuffle, etc..
- The default music source in DF is coded as spotify.  See Default Welcome Intent in the parameters section $lms_source default value.  You can change the default value from spotify to lms, otherwise every time you start the app from google home you will have to day "set source to lms" before you can queue any music
- I assume you get the same error if you try to simply set the volume by voice.
- in DF when you perform a set of commands you can press the Diagnostic Info button and call up the json build being sent to HA to confirm it seems right (should contain query result and the details you asked for)
- I assume you get the same error if you try to simply set the volume by voice.  
- if you set your HA logging to "info" can you see what the log says then.  You should be able to see the json being sent (or not) to HA.
- finally you could add a notification command to the beginning of the lms_control script to ensure it is being called up by your fullfillment and that its just the rendering of the json build that is failing.  

Let me know how that works out and I will try to dig into deeper later tonite.  More log details would be helpful.

**Comment by ynot123** [comment]
Very good to hear.  You are the first to my knowledge to install it.  So some learning curves :).

I will note the V2 thing for DF in the install notes later tonite or tmo.

As for radio stations, not sure it's mentioned but I cheated.  Essentially radio stations are pre-defined in LMS as a playlist with following the naming format:  Radio_StationName all in Title Case.  So some of mine include:  

         Radio_Cbc, Radio_Q92, Radio_Country_Classics

Seemed like the easiest way to get there from here.  This way all the linking is inside LMS.

Enjoy.  Ynot.

**Comment by ynot123** [comment]
Yes noticed that today when diagnosing your issue outlined above. Its a non critical error trying to set the volume  and other numerical inputs to ' ' when they are not specified in the google commands.  I would need to do some pre-eval to get around it but works as-is at this point.  I will put it on a list to fix.  Thanks.

**Comment by ekkesa** [comment]
No problem - This is an amazing piece of work. I was in the infancy stage of starting to build something similar, but nothing on this scale. I was planning on butchering in some hardcoded commands to play a few radio stations. One can see this really took some proper thinking through - Well done!

Appreciate your quick feedback and help!

**Comment by ynot123** [comment]
Thank you I appreciate the feedback.  The Google Home intrigue me, started with IFTTT but that wasn't flexible enough for my liking.  This has been in the works for about 2 months or so.  I am brand new to all these tools (HA, DF, GH) so it certainly was a bit of a challenge.  

Now I need to dream up some further uses.  Take care and enjoy.  Ynot

**Comment by ynot123** [comment]
FYI, 
The file `script_lms_controls.yaml` has been updated to prevent those errors in the log that were noticed yesterday from trying to set blank values. 
Ynot

**Comment by ekkesa** [comment]
Awesomeness! I'm updating it now...

Radio stations still seems not to work though even with the Playlist created in LMS

**Comment by ynot123** [comment]
I have added the radio station `947 94.7 (Top 40 & Pop Music)` in my config and it seems to be working fine.  So the steps were:
- in LMS play the radio station on your favorite player
- save the player's queue (which is only the radio station) as a playlist called `Radio_947 ` (not saving in presets but as a playlist)
- then the voice command is:  play radio station nine hundred and forty seven

I did the same with the Jacaranda station `Radio_Jacaranda` and it worked as well.

A quick way to check is look at the HA GUI, the playlist field will be updated with the name of the radio station (ie: 947 or Jacaranda).  If it's correct there it should go.  Using simple names for radio stations leads to a better experience.

**Comment by ekkesa** [comment]
All working now - I had permission errors on the playlist directory. Never used playlists before, and the LMS web interface didn't give any errors. It created the playlist entry in the DB, but nothing to fulfill the request once called. 

Sorted out the permissions, recreated the playlists and it worked 1st time. ;-)

Have you thought of streamlining the DF that one can call this directly? e.g: Hey Google, Ask LMS Commander to play artist Nirvana in the living room with shuffle on. OR Hey Google, Ask LMS Commander to set living room volume to 60%

**Comment by ynot123** [comment]
Looking into it a bit, a simple streamline to get you in with the proper mediaplayer (without it asking) would be:  "Ask LMS commander for the kitchen".  In order to make this work the default intent needs to be changed to  `for the <player name>` rather than `LMS commander for the <player name>`.  

As for deeper intents you're quite right, that would take some thinking.  Not sure I could handle that many differing types of requests reliably with a simple default intent and I can't see a way to directly bypass the default intent and go right into the app (maybe follow-up intents).  But likely I could handle a couple of simple ones like:

- for the player_name (to set destination)
- set volume to xx for the player_name

**Comment by ynot123** [comment]
Nice that works, seems simple enough.  Never used an implicit intent but will look it up.  

To sanitize DF simply modify the webhooks to remove your HA_Link and HA_API_Password.  

For more detailed LMS work like syncing, building playlists, etc I personally prefer to use the LMS interface directly as it provides more control, precision and easier to query stuff, mix and match and ensure you have the right thing.

FYI, playlists are cleared automatically when using the play command with HA/GH.

Thanks for the help.  Feel free to show off what you build for this in the future and perhaps I can add some (with your permission of course) to the project.

Take care.  Ynot

**Comment by ynot123** [comment]
Sounds good.  And i do agree LMS interface is not very functional on a phone type device.  I use Squeeze Ctrl for that.  Nice interface for linking players, clean and simple.

**Comment by ekkesa** [comment]
Awesome - I will definitely track it. 

Enjoy your time off...

**Comment by ekkesa** [comment]
Hi,
Yes I used the mac addresses to sync. I added a custom attribute to the media_player.x in customize.yaml

media_player.daspoort:
  friendly_name: Daspoort
  playerid: aa:aa:c0:0a:c5:ab

I then called the attribute in a script with {{ states.media_player.daspoort.attributes.playerid }}.

Hope it helps...

I have an additional idea which could be incorporated- I have an input_select which plays a url on the selected speaker. The values of the input select is a list of radio stations which is then kicked off from a script. Here is a copy of the script:

    alias: Play Radio on Speakers
    sequence:
      - service: media_player.volume_set
        data:
          entity_id: media_player.sitkamer
          volume_level: '0.70'
      -  service: media_player.volume_set
         data:
           entity_id: media_player.picade
           volume_level: '0.70'
      -  service: media_player.volume_set
         data:
           entity_id: media_player.daspoort
           volume_level: '0.70'
      -  service: media_player.play_media
         data_template:
           entity_id: >
            {% if is_state("input_select.radio_knop", "Daspoort") %} media_player.daspoort
            {% elif is_state("input_select.radio_knop", "Living Room") %} media_player.sitkamer
            {% elif is_state("input_select.radio_knop", "Picade") %} media_player.picade
            {% elif is_state("input_select.radio_knop", "PiInTheSky") %} media_player.testspeaker
            {% elif is_state("input_select.radio_knop", "Everywhere") %} media_player.kakofonie
            {% endif %}
           media_content_id: >
            {% if is_state("input_select.radio_station", "Jacaranda") %} http://opml.radiotime.com/Tune.ashx?id=s6410&formats=aac,ogg,mp3,wmpro,wma,wmvoice&partnerId=16&serial=2d444aedc36f4d5f2d3e7d45d67d7683
            {% elif is_state("input_select.radio_station", "Highveld 94.7") %} http://opml.radiotime.com/Tune.ashx?id=s6400&formats=aac,ogg,mp3,wmpro,wma,wmvoice&partnerId=16&serial=2d444aedc36f4d5f2d3e7d45d67d7683
            {% elif is_state("input_select.radio_station", "Impact") %} http://opml.radiotime.com/Tune.ashx?id=s6412&formats=aac,ogg,mp3,wmpro,wma,wmvoice&partnerId=16&serial=2d444aedc36f4d5f2d3e7d45d67d7683
            {% elif is_state("input_select.radio_station", "702") %} http://opml.radiotime.com/Tune.ashx?id=s25727&formats=aac,ogg,mp3,wmpro,wma,wmvoice&partnerId=16&serial=2d444aedc36f4d5f2d3e7d45d67d7683
            {% elif is_state("input_select.radio_station", "RSG") %} http://opml.radiotime.com/Tune.ashx?id=s143888&formats=aac,ogg,mp3,wmpro,wma,wmvoice&partnerId=16&serial=2d444aedc36f4d5f2d3e7d45d67d7683
            {% elif is_state("input_select.radio_station", "Groot FM") %} http://opml.radiotime.com/Tune.ashx?id=s8386&formats=aac,ogg,mp3,wmpro,wma,wmvoice&partnerId=16&serial=2d444aedc36f4d5f2d3e7d45d67d7683
            {% elif is_state("input_select.radio_station", "Classic FM") %} http://opml.radiotime.com/Tune.ashx?id=s24967&formats=aac,ogg,mp3,wmpro,wma,wmvoice&partnerId=16&serial=2d444aedc36f4d5f2d3e7d45d67d7683
            {% elif is_state("input_select.radio_station", "Radio 538") %} http://vip-icecast.538.lw.triple-it.nl:80/RADIO538_MP3
            {% elif is_state("input_select.radio_station", "Veronica") %} http://8543.live.streamtheworld.com/VERONICACMP3
            {% elif is_state("input_select.radio_station", "Sky Radio") %} http://8623.live.streamtheworld.com:80/SKYRADIOAAC_SC
            {% elif is_state("input_select.radio_station", "SLAM! Hardstyle") %} http://vip-icecast.538.lw.triple-it.nl/WEB17_MP3
            {% elif is_state("input_select.radio_station", "Sleep Radio") %} http://37.59.28.208:8722/stream
            {% elif is_state("input_select.radio_station", "Ambient Sleeping Pill") %} http://perseus.shoutca.st:8447/h
            {% elif is_state("input_select.radio_station", "Radio Art - Sleep") %} http://live.radioart.com/fSleep.mp3
            {% elif is_state("input_select.radio_station", "Calm Radio - Sleep") %} http://streams.calmradio.com/api/39/128/stream
            {% elif is_state("input_select.radio_station", "Dinamo.FM Sleep") %} http://channels.dinamo.fm/sleep-aac
            {% endif %}
           media_content_type: 'audio/mp4'

**Comment by ynot123** [comment]
Thanks that's kinda what i figured.  I was just trying to make the code as efficient as I can and limiting the data entry for each user. 
 
**Update:**
The linking and implicit intent commands seem to work well, with some additional streamlining done in DF and the ability to add more intents which can trigger the same or different commands in the HA scripts.  Each intent now has a `lms_command` parameter which can be set to trigger the required actions in HA. 

The all intents are both explicit and implicit.  When called in implicit fashion `Hey goggle ask LMS Controls to play artist Pink Floyd in the mediaroom`, once the command executes DF waits for 10 seconds or so for other commands like ` set volume to 40` or `set shuffle on`, etc.  If no input is given in the 10 second period, it exits automatically with a "goodbye".

As for the radio links and other simple LMS specific GUI tasks, I will have to think about that.  Wasn't really part of the plan initially at least.
