### ISSUE TITLE
Home Assistant Docker Dependencies

### ISSUE THREAD

**Issue by jollybully** [ynot123/LMS_Controls#10]
Is there any way to make this package natively compatible with the official homeassistant docker image (short of building a new image)? 

I'm currently manually installing both jq and ncat (as well as modifying line 37 in qry_player_sta.sh) each time I update the container.

Again, great work! I appreciate all the help so far.

**Comment by jollybully** [comment]
Apologies - ncat is already installed in the official image. Modifying the line 37 to use ncat rather than nc fixes the errors in the log. 

It seems that adding a shell command to run on homeassistant start to install jq works, albeit in a slightly hacky fashion. Seems like a good way to break something in the future. 

`shell_command:
  install_jq: 'apt-get update; apt-get install -y jq; apt-get clean;'`

**Comment by ynot123** [comment]
Will have to do a bit of research on the differences between Hass.io and Home Assistant Docker images.  
Surprising one image would use nc while the other ncat.  I'm pretty sure I could work out a consistent method using "which".  

jq however is another matter.  Definitely a requirement to ease some JSON programming work.  

I will take this into consideration if and when I make another revision.   Can you fill me in on exactly which images you are running and what hardware / OS.  That way I confirm what's contained within those images.

Thanks, Ynot.

**Comment by jollybully** [comment]
I'm using the official docker image (homeassistant/home-assistant) on Unraid 6 / Xeon.
Working fine using the above shell_command workaround. 

Thanks
