### ISSUE TITLE
Sensors missing

### ISSUE THREAD

**Issue by Rafaille** [ynot123/LMS_Controls#11]
Hi ynot,

First of all, fantastic work on this project, I have been using LMS_Controls regularly over the last month and I must say it is definitely one of the most both useful and fancy bit of automation I have ever tried.
I just updated to the latest version and I find your new functions very interesting, especially the follow-up in dialogflow.

But since this is an issue section, let's get on with it:
Is it just me doing something wrong or there is not any sensors declared in the config file?

I just noticed while reading my HA log file at latest reboot that the automation "LMS GUI update player values" was complaining about the raw_volume value not being a float value and then after adding a 'float' filter in the value_template section of the aforementioned automation that there was no sensors declared altogether.

I cannot see any line corresponding to sensors in the config file and obviously the sensors called in the automation cannot be found in the 'state' lists in HA.

This is not a big concern to me as I am not using the GUI functions too much but mostly google assistant and the Squeezer app on my phone (great app by the way), but I thought I would report the issue anyway.
That said, it can affect any scripts/automations that are based on those sensors.

Again, minor issue, big kudos to you, amazing work here!

Alex

**Comment by ynot123** [comment]
Glad to see your enjoying the tool.  Makes the effort worth it :).

So the sensors are created dynamically using the shell script files (/config/shell/*.sh).  In particular sensor.raw_volume is created or updated every time the **qry_player_stat.sh** script runs.  In fact several sensors are created / updated including sensor.raw_volume, sensor.raw_shuffle, sensor.raw_repeat and sensor.raw_sleep. 

I haven't noticed any HA log complaints about sensor.raw_volume not being a float in my installations.  You can test the script file on it's own in your HA terminal in the shell directory as per the troubleshooting guide and see if it's working properly.  Once executed, you should be able to see the sensors in HA.  In my installation they show up at the top of the screen using the following link:
https://yourdomain.duckdns.org/states

I will leave this issue open for a few days while I review in case this is a breaking change from HA, but so far doesn't appear to be.

Ynot.

**Comment by ynot123** [comment]
Hi Alex,
You're quite right about the path thing, I actually forgot about that being hard coded in the shell files.  I will put in 2 cents regarding this requirement in the install document.  As for why it's not working for you, I am assuming (based on your description) the current player's mac address is not being passed to the script properly.  A check would be:

- In the lmscontrols.yaml file in the customize section did you remember to edit the player_id's to reflect the proper mac addresses.  So for instance:
```
    media_player.familyroom:
      name: Family Room
      playerid: bb:bb:db:xx:xx:xx
      sync_stat: false 
```

- If this has been done then you could turn on the logger component for the shell commands and review the logs to ensure the value is being passed to the script and what the resulting output is.  To enable the logger, in your configuration.yaml file the following entry is required:
```
logger:
  default: critical
  logs:
    homeassistant.components.shell_command: debug
```
That should provide some insight into what is going on.

**Comment by Rafaille** [comment]
Hi Ynot,

My player's MAC address is actually correctly passed to the shell script.
It is the shell script itself that does not return the expected result when the MAC is provided as an argument, but it does return the right values when executed without the MAC address.

Here is the output of the shell script with the MAC:
(I edited MAC address, HA token, and domain for obvious privacy reasons but I checked and they are all ok)

homeassistant@max2play:~/.homeassistant/shell $ bash qry_player_stat.sh aa:bb:cc:dd:ee:ff
lms_username is: null
login is: not required and lms_secure is: 0
HA Token is: xxxxxxxxxxxx
My Domain is: xxx.duckdns.org
My lms_ip: 192.168.1.64
My lms_cli_port: 9090

Query is: b8%3A27%3Aeb%3Aaa%3A33%3A84 status
qry_player_stat.sh: line 44: [: too many arguments
qry_player_stat.sh: line 50: [: too many arguments
No Sleep Parameter Found - setting to 0
volume:b8%3A27%3Aeb%3Aaa%3A33%3A84 status
shuffle:On
repeat:On
sleep:0
{"attributes": {}, "context": {"id": "d7659bb2552a4711b87b1d130d395660", "user_id": "22c80ff00fb74e50b98c50abac6cd669"}, "entity_id": "sensor.raw_volume", "last_changed": "2019-02-02T12:50:56.866050+00:00", "last_updated": "2019-02-02T12:50:56.866050+00:00", "state": "b8%3A27%3Aeb%3Aaa%3A33%3A84 status"}
{"attributes": {}, "context": {"id": "3728db4210624a81aa5fedb885dc1398", "user_id": "22c80ff00fb74e50b98c50abac6cd669"}, "entity_id": "sensor.raw_shuffle", "last_changed": "2019-02-02T12:50:57.343194+00:00", "last_updated": "2019-02-02T12:50:57.343194+00:00", "state": "On"}
{"attributes": {}, "context": {"id": "ad272e5189e24e3e82b0c69b460cb4c7", "user_id": "22c80ff00fb74e50b98c50abac6cd669"}, "entity_id": "sensor.raw_repeat", "last_changed": "2019-02-02T12:50:57.505816+00:00", "last_updated": "2019-02-02T12:50:57.505816+00:00", "state": "On"}
{"attributes": {}, "context": {"id": "b7539fa785244a1abaed6e8843ce81a7", "user_id": "22c80ff00fb74e50b98c50abac6cd669"}, "entity_id": "sensor.raw_sleep", "last_changed": "2019-01-31T16:35:45.348763+00:00", "last_updated": "2019-01-31T16:35:45.348763+00:00", "state": "0"}


Now if I run the script without the MAC, it looks ok and returns the right values, here is the output:

homeassistant@max2play:~/.homeassistant/shell $ bash qry_player_stat.sh
lms_username is: null
login is: not required and lms_secure is: 0
HA Token is: xxxxxxxxxxxxx
My Domain is: xxx.duckdns.org
My lms_ip: 192.168.1.64
My lms_cli_port: 9090

Query is: b8%3A27%3Aeb%3Aff%3A66%3Ad1 status player_name%3Alivingroom player_connected%3A1 player_ip%3A192.168.1.64%3A51788 power%3A1 signalstrength%3A0 mode%3Aplay time%3A190.414274110794 rate%3A1 duration%3A249.946 can_seek%3A1 mixer%20volume%3A70 playlist%20repeat%3A0 playlist%20shuffle%3A0 playlist%20mode%3Aoff seq_no%3A0 playlist_cur_index%3A11 playlist_timestamp%3A1549109750.69059 playlist_tracks%3A22 digital_volume_control%3A1
No Sleep Parameter Found - setting to 0
volume:70
shuffle:Off
repeat:Off
sleep:0
{"attributes": {}, "context": {"id": "9e52e8ea53fc447393bed531cdb7bd7d", "user_id": "22c80ff00fb74e50b98c50abac6cd669"}, "entity_id": "sensor.raw_volume", "last_changed": "2019-02-02T12:56:00.591643+00:00", "last_updated": "2019-02-02T12:56:00.591643+00:00", "state": "70"}
{"attributes": {}, "context": {"id": "e253c293e29b4b24b78574a6fbb5595c", "user_id": "22c80ff00fb74e50b98c50abac6cd669"}, "entity_id": "sensor.raw_shuffle", "last_changed": "2019-02-02T12:51:00.536866+00:00", "last_updated": "2019-02-02T12:51:00.536866+00:00", "state": "Off"}
{"attributes": {}, "context": {"id": "e6199b2f249b422d89f5be01186d25d8", "user_id": "22c80ff00fb74e50b98c50abac6cd669"}, "entity_id": "sensor.raw_repeat", "last_changed": "2019-02-02T12:51:00.942407+00:00", "last_updated": "2019-02-02T12:51:00.942407+00:00", "state": "Off"}
{"attributes": {}, "context": {"id": "b7539fa785244a1abaed6e8843ce81a7", "user_id": "22c80ff00fb74e50b98c50abac6cd669"}, "entity_id": "sensor.raw_sleep", "last_changed": "2019-01-31T16:35:45.348763+00:00", "last_updated": "2019-01-31T16:35:45.348763+00:00", "state": "0"}


Then again, not a big issue for me, as running the script without the MAC is fine by me, as I only have one player, but now I just need to know why it does not work :)

**Comment by Rafaille** [comment]
It is getting weirder...

I was just passing by here to see whether you had replied and realised that I had forgotten to edit out some parts of the script output to hide my MAC address (oops!).
While doing so, I noticed that when the qry_player_stat.sh script is manually run without any argument (no MAC) then it takes as query a MAC address which is different from the one mentioned in the media_player state attributes!
A quick ifconfig confirmed that the MAC address from the state attributes is ok but also reveals that the other address (the one the script gets from... somewhere?!) is my wlan0 MAC address.
Now the problem is, I am not using the wifi on the RPi as it is plugged in my home router through ethernet cable.

Any ideas??

**Comment by Rafaille** [comment]
Hi,

You couldn't be more right!
Although server and player are running on the same device, for some reason the server is identified as one MAC (the eth0 one, also the one listed in HA as the media_player entity) and the player is identified as another (the wlan0 one).

Your script is able to get the player's MAC and then returns good results whereas when fed with the server's MAC (from the player_id field of the entity in HA) it crashes.

Now I guess I need to understand why on earth the player and server have different MACs. Might be a specificity of Max2play...

Thanks for your help all the way through.

Please keep maintaining this soft, it really kicks ass!

Cheers

**Comment by ynot123** [comment]
Very good sounds like that solves it then.  Unless there is something further, I will close this issue.
