### ISSUE TITLE
Hard coded IP in qry_alb_song.sh

### ISSUE THREAD

**Issue by frelev** [ynot123/LMS_Controls#12]
There is a hard coded IP in qry_alb_song.sh, such as:

 query=$(printf "$login_str albums 0 20 artist_id:$art_id search:$2 tags:al \n" | socat stdio tcp:**192.168.0.20:9090**,shut-none )

**Comment by ynot123** [comment]
Dang.  Thanks for the good catch.  That one slipped by me.  Checked back in a day or so and it will be updated to `socat stdio tcp:"$lms_ip":"$lms_cli_port",shut-none`.  Hopefully that's the only one.  :)
