### ISSUE TITLE
"Turn off" behavior 

### ISSUE THREAD

**Issue by frelev** [ynot123/LMS_Controls#14]
It seem that Turn off is behaving strange (for me at least). Its more like it Toggles?
Using DialogFlow:

Status -> Command -> Result
If player is off -> "Turn off office" -> player starts(!)
if player is on -> "Turn off office" -> nothing happens
if player is on -> "Turn off" -> player pauses

is this by design?

Might be related to this:
https://github.com/home-assistant/home-assistant/issues/20537

**Comment by ynot123** [comment]
In Dialogflow, my intent pause_player called using something like:  "Pause the kitchen" which pauses the kitchen player or "Pause player" which pauses the current active player as shown in the HA GUI.  I did put the words turn off in there as well but strictly speaking I shouldn't be using that as its a reserved function in Google / HA and can cause issues.  It seems to work properly for my players but mine are always active, never really "off.  In the scripting it uses the media_player.pause method.

The start_player player intent is basically the exact opposite and in the scripting it uses the media_player.play method.   Again I should not use "turn on player" but rather un-pause or start.

How that actually works inside HA and with LMS is a function of their implementations.  
Ynot..

**Comment by frelev** [comment]
OK! Thank you for the explanation, so its working as intended.
I´ll close the issue,
