### ISSUE TITLE
dialogflow error 206

### ISSUE THREAD

**Issue by tayanov** [ynot123/LMS_Controls#22]
Test from  dialogflow not passed.

 "status": {
    "code": 206,
    "errorType": "partial_content",
    "errorDetails": "Webhook call failed. Error: Failed to parse webhook JSON response: Expect message object but got: null."

**Comment by ynot123** [comment]
Sounds like the webhook isn't typed in properly (or invalid).  Should look something like: 

https://homeassistant.duckdns.org/api/webhook/insert_your_webhook_id_here

Ensure you generated a valid webhook ID and long lived token and that your HA instance is accessible over the internet.

Setup details can be found at:  https://github.com/ynot123/LMS_Controls/blob/master/Installation%20Instructions.md

**Comment by tayanov** [comment]
Hi. When I'm going to https://homeassistant.duckdns.org/api/webhook/insert_your_webhook_id_here
I see "405: Method Not Allowed"

Is it right?

Anyway API v1 will be closed. And what then?

**Comment by tayanov** [comment]
realy i recreate token for webhook and longtime token and recive code 200) thanks
And what with api v2?

**Comment by ynot123** [comment]
I have done some initial testing with V2 API.  It seems to work fine with the latest versions of HA.  Simply press the gear icon and change to V2.  Give it a try.
