### ISSUE TITLE
Breacking change in 0.103.0

### ISSUE THREAD

**Issue by tayanov** [ynot123/LMS_Controls#23]
Squeezebox : media_player.squeezebox_call_method-> squeezebox.call_method([ # 29141](https://github.com/home-assistant/home-assistant/pull/29141) )

Need change at Lmscontrols.yaml
media_player.squeezebox_call_method
to 
squeezebox.call_method

**Comment by ynot123** [comment]
Thanks yes just saw that last night.  Updated the readme file for now.  Will update the code when I get a chance.  Ynot

**Comment by ynot123** [comment]
Code update for service syntax complete.
