### ISSUE TITLE
Support for DialogFlow V2 as V1 no longer available

### ISSUE THREAD

**Issue by DrJohnT** [ynot123/LMS_Controls#24]
I have been setting up LMS Controls on my new Home Assistant instance.  Everything was going swimmingly until I got to:

- Section D - DialogFlow - Agent Creation and Configuration Instructions

The problem is that Google will no longer allow me to create a V1 agent.  All new agents need to be in V2.  I tried changing the package version, but that did not help.

When are you intending to release an updated LMS Controls Agent??

**Comment by ynot123** [comment]
Did you create a V2 agent and then try to restore or import the LMS_Control_Agent - Sanitized.zip file?  That seem to work for me.  You can then change the agent back to V2 and it should work.  Let me know.  If not, I can try to post a newer V2 agent but that might take me some time as I am away for the next bit.  Let me know.  Ynot.
