### ISSUE TITLE
How to link to google

### ISSUE THREAD

**Issue by andrewstech** [ynot123/LMS_Controls#29]
dialogflow is no longer an option when creating the skill. So now im confused on how to intergrate it.

**Comment by ynot123** [comment]
humm  haven't tried to develop anything new lately.  But I can still modify my project easily enough.  Everything appears to be working properly.

**Comment by andrewstech** [comment]
Thankyou it seems like Google has made actions on Google into it's own platform. Good luck 😀

**Comment by ynot123** [comment]
It has always been it own platform.  But the integration of Dialogflow with google assistant still appears to be available on the dialoglfow platform.  In Dialogflow select google integration, pick the intents to publish (all of them) and the use the TEST function and it should build and populate your actions in the Google platform.

It looks like Webhooks are not directly implemented on the Google Actions platform so I believe the best way to go for now at least is use the dialogflow platform and select the google integration.
