### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by gianky69** [ynot123/LMS_Controls#4]
Hi, I'm Giancarlo from Italy.
I'm trying to translate entities and intents in order to use your work with italian language in Google Assistant.
I'm not sure if I could just translate only these componentes, with new "italian" speaking in DialogFlow (using english as default language), not changing the "lang" value from "en" to "it" in all .json files.
Could you help me?
Thanks a lot!

PS: if it'll work, I'll send you my translation in order to commit into your work ;-)

**Comment by ynot123** [comment]
Hi. I will be on the road on holidays and no access for the next couple of weeks so won’t be able to try anything.  I would assume you can add a language and the translation may even be automatic.  Give it a shot.  Not sure how it works.   Let me know how you make out.  If you can’t figure it out.  I will take a shot at I too. Then end of September 

Thanks. Yvon

**Comment by ynot123** [comment]
A little research and I stumbled into this.  [Languages in Dialogflow](https://dialogflow.com/docs/reference/language).  Looks like Italian is one of the supported base languages so you should be able to provide the basic training and response phrases in Italian and not have to change the parameters or the webhooks.  Let me know how you make out.  Ynot.

**Comment by gianky69** [comment]
Hi, I've worked with Dialogflow: added italian language and provided training/responses, without changing parameters nor webhooks. Next I've tested it with Google Assistant online test and everything (perhaps) seems ok.
But when I try to give commands via my Google Home Mini, I can only set power on or off to squeezeboxes (I have 4), but when I send commans like "suona artista Marillion in studio" (play artist Marillion), the response is "ok" from Google Home but nothing happens.
I'll investigate...

**Comment by ynot123** [comment]
When addressing the app using google home or mini.  The phrase is:  "Hey Google, ask LMS Controls (or the name of your app) to play artist Marillion" which is an implicit intent or call up the app first then issue your command like:  "Hey Google, talk to LMS controls", wait for the acknowledgement, then say something like "Play artist Marrillion".  This would be an explicit intent.  There are several example statements available here:  [Example Commands](https://github.com/ynot123/LMS_Controls/blob/master/example_commands.md)

**Comment by gianky69** [comment]
My phrase is "Hey Google, parla con LMS Control" then "Usa Musica flac" (my
LMS server), then "Suona artista Marillion in studio". The answer is "Ok,
suono Marillion in studio"... but nothing happens...

++++++++++++++++++++++++++++++++++++++++++++++++++++++
Il blog di mountain bike MIB: mib-trieste.it
Il mio piccolo blog fotografico: giancarlomassari.blogspot.com



Il giorno mar 4 set 2018 alle ore 12:57 ynot123 <notifications@github.com>
ha scritto:

**Comment by ynot123** [comment]
Did it work properly in english?

You can try reading through the [troubleshooting](https://github.com/ynot123/LMS_Controls/blob/master/troubleshooting.md) document to start.  The first step is to check to make sure the HA GUI is working with play, pause, etc..  If good then check the queuing functions for the HA GUI.  If good then need to review what's happening at the dialogflow level.  Of course, the queue status, etc.  can be monitored by the LMS front-end as well.

A pretty detailed troubleshooting sequence can be seen in the previous issue thread.

**Comment by gianky69** [comment]
Tomorrow I’ll do an appropriate check. And then I’ll give you a feedback.
Thanks a lot for you support

Giancarlo

**Comment by gianky69** [comment]
My squeezeboxes, from Home Assistant sync, are like “switches” in Google Assistant. Could it be the trouble?

Inviato da iPhone

**Comment by ynot123** [comment]
Review the ha GUI graphic. The suns works like a switch sync on or off

**Comment by gianky69** [comment]
Yes, I know it. But the problem remain... I can only send commands like
"on" and "off" to all squeezeboxes, the other commands seems accepted by
Google Assistant, but nothing happens. I'll try to change language to my GA
in english...

++++++++++++++++++++++++++++++++++++++++++++++++++++++
Il blog di mountain bike MIB: mib-trieste.it
Il mio piccolo blog fotografico: giancarlomassari.blogspot.com



Il giorno ven 7 set 2018 alle ore 02:49 ynot123 <notifications@github.com>
ha scritto:

> Review the ha GUI graphic. The suns works like a switch sync on or off
>
> Sent from my iPhone
>

**Comment by ynot123** [comment]
OK,
So follow the basic trouble shooting steps as laid out in the troubleshooting doc. The basic steps are:

- Make sure HA GUI works with LMS server on its own (no voice stuff)
- Test play, pause, next track, volume, shuffle, repeat, etc..
- Test the query functions for artist, album,song, playlist

Let me know the result, if that is good then HA is talking properly, if not troubleshoot here first.

If that works then issues would be between google dialogflow and home assistant.  To check that issue your command and look at the HA GUI to see if your query info appears there under album, artist, song, playlist.  If this fails then issues are likely with the webhook or HA scripts.

Finally, I assume you carefully followed the installation instructions modifying the files as listed in the instructions.

Yvon

**Comment by gianky69** [comment]
Some weeks without access to my system, I'll be back asap

**Comment by ynot123** [comment]
Have you made any progress here.  If I don't hear back, I will close this issue.  You can re-open when you gte back to it if needed.  Thanks, Ynot

**Comment by gianky69** [comment]
I’ve done some tests with no luck , but I’ve discovered you changed some elements in December. So I’m going to do a fresh reinstallation and let you know...

**Comment by ynot123** [comment]
I would wait until the next release at the end of the month

**Comment by gianky69** [comment]
Today I've reinstalled all your files and updated my configurations (HA and Dialogflow). I'm working now on translation... But I've a problem in HA: using the UI commands, I can only ask to play an artist (es: Muse) and the response is a full "playlist" playing on my Squeeze. If I insert also Album name and select "Play album" nothing happens (seems so also for Song or Playlist). Any help?

**Comment by ynot123** [comment]
Likely your shell script files are not running properly.  Review this troubleshooting document, ensure you have your HA_token, nc command works and proper url link and ip address for lms.  

  https://github.com/ynot123/LMS_Controls/blob/master/troubleshooting.md

Also as mentioned earlier, I will be releasing a revised version nearing the end of the month which will be accompanied by a more detailed installation document, better error checking, less data entry, etc..

You can also enable more detailed loggin by adding the following entry into your configuration.yaml file.  Enable the various logs and view the results,
```
logger:
  default: critical
#  logs:
#    homeassistant.components.shell_command: debug
#    homeassistant.components.intent_script: debug
#    homeassistant.components.dialogflow: debug
#    homeassistant.components.media_player.squeezebox: debug

```

**Comment by gianky69** [comment]
Looking in LMS logs (Squeezebox server side), I get this error:

```
> [19-01-14 13:17:08.3603] Slim::Control::Request::execute (1888) Error: While trying to run function coderef [Slim::Control::Commands::playlistcontrolCommand]: [Can't call method "title" on an undefined value at /volume1/@appstore/SqueezeCenter/Slim/Control/Commands.pm line 2021.
> ]
> [19-01-14 13:17:08.3612] Slim::Web::JSONRPC::requestMethod (456) Request failed with error: Bad dispatch!
```

**Comment by ynot123** [comment]
Yes,  likely sending an empty string to LMS, which would mean the shell script(s) isn't running correctly (bad token, bad client_id/secret for Spotify, bad lms ip/port, command nc or jq not available, etc..) or shell script not being executed at all (bad path).  Use the troubleshooting doc and:

1. Open a shell inside your HA and run the shell scripts manually and look at the results and ensure the query is successful and sensors are being published with no errors, or;
2. Enable the logs above and look at the results from the shell scripts for items outlined above.

Option 1 is a little easier to read.  
Note:  if this is a Docker installation, you can open a shell into the Docker using this command:  **docker exec -it homeassistant bash**

**Comment by gianky69** [comment]
Solved. The problem was the duckdns connection... I need not only `HA_link` change in `https://HA_Link.duckdns.org/api/states/sensor.art_ID? -H "Authorization Bearer $HA_Token"` but also i need to add `my_port_number` after `.org`
Now I going to try Google integration

**Comment by ynot123** [comment]
Are you using non-standard ports?  Have you tried modifying the baseurl setting in configuration.yaml instead?  Just asking as this is the first I've heard of having to use a port number for access.  Thanks, Ynot.

**Comment by gianky69** [comment]
The base_url in configuration.yaml has port number (standard, 8123).
Meanwhile I've tested DialogFlow-GA and seems to work!

**Comment by ynot123** [comment]
If you have the time, please try the following settings:  **base_url: yourdomain.duckdns.org**

And in a shell file remove the port# after the url link and see if it works.  That is the basic config many users are running.  You were the first to say a port setting for the HA URL link in the shell files is required.

Thanks, Ynot.

**Comment by frelev** [comment]
I just want to chip in regarding translations. I added Swedish in Dialogflow (which is supported) but it doesnt work. For all commands I get "Can you repeat", I didnt hear you etc (In Swedish ofc). But the English commands work fine.
I have not tried with Google Home yet

**Comment by frelev** [comment]
@gianky69  so when you have added IT to dialogflow your able to push your app to GA?
You do not recieve the same problem I`m facing here?
https://github.com/ynot123/LMS_Controls/issues/15

**Comment by remym777** [comment]
thanks to ynot123 i finally succeded to make everything work in english. A huge thanks to him and for it's patience. Like @frelev or @gianky69 i'm going to try put it in an other langage: french (european). From what i've read on google support, i have to be sure that the part 'Training phrases' are filled in the other language (french in my case) in the intents that are going to be used in Google Assistant.

Is that it or there is something much easier?

If that's it and if i have time to translate everything i could share it for the other french.....

**Comment by ynot123** [comment]
Glad to hear you got it going.  Generally its supposed to be fairly easy.  Too bad about the rabbit hole we went down.  Now we know, http errors are probably the wrong port. :).

I have no experience yet on the translation side of things.  I was going to attempt french myself but haven't gotten around to it, not to mention " Mon français fait pitié".  Good luck and keep me posted.  If you think you have a working framework in Dialogflow, feel free to forward it on for review and inclusion as an option.

**Comment by remym777** [comment]
ok 
it looks like from what i read, that i just have to add at least one training phrases for each case in french...
I'm going to give it a shot and keep you in touch

**Comment by ynot123** [comment]
That part (training phrases) should work, it's the reference to spelling of french artists, albums, songs, etc.. that might be tricky.   I think you will need to ensure the Google AI knows you're speaking french.  

In my home, my wife doesn't speak french, so flipping googlehome to french might make my life difficult.  Happy wife, happy life.

**Comment by remym777** [comment]
from what i've already tested, it's possible to have two languages or more at the same time on the google home. It's start with the default one but detect straight away if it's a different one on the way

**Comment by remym777** [comment]
Hi, i've translated at least one sentence on each intents in the training phrases. And mostly it works great ... to be perfect i probably have to multiply the different training phrases but at this step it work pretty good.

I encounter nevertheless one main problem. on some commands(several) like play artist, my google home says : (in french but i translate in english) : "LMS control doesn't respond please try later" but still do the action i've asked.. 
Any one has an idea?

**Comment by remym777** [comment]
Hi, i think i find the problem bu not the issue. under dialogflow i entered un training sentence in french with 3 actions and parameters.(artiste/mediaplayer/shuffle on)
when i send the project to "actions on google" the 2 last actions just disappeared when i check in the action part of "actions on google" page.
is there a reason et a way to avoid this. If i'm not clear enough here are photos....

https://image.noelshack.com/fichiers/2019/08/6/1550956896-diagflow.jpg   (3 actions/paramèters)

https://image.noelshack.com/fichiers/2019/08/6/1550956895-google-french.jpg ( only action/paramètres)

insitially in english the 3 were present:
https://image.noelshack.com/fichiers/2019/08/6/1550957486-google-english.jpg

merci d'avance

**Comment by remym777** [comment]
I think i found the problem but still looking for the solution...
For the play_artist for instance.
When in dialogflow i translated the sentence in french (in the training phrases), like your did in english i put 3 actions/parameters.
https://www.noelshack.com/2019-08-6-1550956896-diagflow.jpg

but when i press "how it works in google" and access to the "actions on google" part actions and i check play_artist my sentence appears with only 1 action/parameters et not 3 asit was in dialogflow.

https://www.noelshack.com/2019-08-6-1550956895-google-french.jpg

and your initial sentence in english stay with the same number of action in dialogflow or in "action on google"

https://image.noelshack.com/fichiers/2019/08/6/1550957486-google-english.jpg

Somebody know what i did wrong ?

**Comment by remym777** [comment]
so apparently the problem comes from the action/parameter in dialogflow...
when i try a sentence "in the try it now" the actions missing in the "actions in google" are infact not responding in dialogflow (this the right column of the image).

https://image.noelshack.com/fichiers/2019/08/7/1550994501-probleme-dialogflow-carre-rouge.jpg

any idea? this time i'm stuck...

**Comment by paolo1983** [comment]
> Hi, I'm Giancarlo from Italy.
> I'm trying to translate entities and intents in order to use your work with italian language in Google Assistant.
> I'm not sure if I could just translate only these componentes, with new "italian" speaking in DialogFlow (using english as default language), not changing the "lang" value from "en" to "it" in all .json files.
> Could you help me?
> Thanks a lot!
> 
> PS: if it'll work, I'll send you my translation in order to commit into your work ;-)

Sei riuscito a farlo andare in italiano?

**Comment by gianky69** [comment]
Alla fine ci ho rinunciato...

**Comment by paolo1983** [comment]
> Alla fine ci ho rinunciato...

A me basterebbe un solo comando. Dare il play di un brano o di un album su un unico player predefinito. Possiamo sentirci via mail? paolofaz@libero.it

**Comment by ynot123** [comment]
You should be able to make this work by changing your language in Dialogflow to Italian and re-writing the phrases to suit.  Start by trying a simple command or two.  I did do some work in the French translation and it basically worked though I believe there was some issues with implicit intents.  Explicit intents did work

**Comment by paolo1983** [comment]
> You should be able to make this work by changing your language in Dialogflow to Italian and re-writing the phrases to suit. Start by trying a simple command or two. I did do some work in the French translation and it basically worked though I believe there was some issues with implicit intents. Explicit intents did work

Thanks. I Need only two command in italian:
1)Google stop the music
2)Google play artist/album/Song
What file i have to change?

**Comment by ynot123** [comment]
As mentioned, you need to open up the dialogflow project, change the language, modify the phrases you are interested in and test.  Your Google commands may need to be explicit so in english that might be something like:  "Hey Google talk to LMS controls.  Pause the player"

**Comment by paolo1983** [comment]
> As mentioned, you need to open up the dialogflow project, change the language, modify the phrases you are interested in and test. Your Google commands may need to be explicit so in english that might be something like: "Hey Google talk to LMS controls. Pause the player"

Ok. It seems work

**Comment by ynot123** [comment]
Glad to hear it.  Are you able to do implicit intents or is it simply explicit intents?

Implicit:  "Hey google ask LMS Control to play artist Supertramp in the kitchen"

Explicit:  "Hey Google talk to LMS Controls."   "Play artist Supertramp in the kitchen"

**Comment by paolo1983** [comment]
> Glad to hear it. Are you able to do implicit intents or is it simply explicit intents?
> 
> Implicit: "Hey google ask LMS Control to play artist Supertramp in the kitchen"
> 
> Explicit: "Hey Google talk to LMS Controls." "Play artist Supertramp in the kitchen"

Implicit not works. Why?

Another thing: why the app answers me the Italians phrases that i wrote with an english pronountiation?

**Comment by paolo1983** [comment]
> Glad to hear it. Are you able to do implicit intents or is it simply explicit intents?
> 
> Implicit: "Hey google ask LMS Control to play artist Supertramp in the kitchen"
> 
> Explicit: "Hey Google talk to LMS Controls." "Play artist Supertramp in the kitchen"

Yesss work implicit and explicit. Perfect! Great job

**Comment by ynot123** [comment]
OK, I will close this item then as it sounds like the Italian translation is workign for you,.  If you could kindly forward a copy of the dialogflow project at my email (yland@vianet.ca) I will review and see if it can be integrated into my copy
