### ISSUE TITLE
Common variables

### ISSUE THREAD

**Issue by chelliwell** [ynot123/LMS_Controls#5]
Hi, Just working through installing this on my system. One thing that struck me is that there's a lot of places to "insert your own value here". It occurred to me that, for the scripts in particular, the settings could be placed once in an inherited/source'd file?
Would also be good if definitions of players could be held or scripted from a single point - to keep the files coherent. I'm sure you've already thought this tho ;)

**Comment by ynot123** [comment]
Thank you for the suggestions.  I will try to implement that in the near future upgrades.  Your quite right, it can be painful.  For the shell scripts I should be able to work something out for sure.
