### ISSUE TITLE
auth errors in new release

### ISSUE THREAD

**Issue by jollybully** [ynot123/LMS_Controls#8]
All of the curl request to HA in the shell directory appear to have too many parenthesis causing auth to fail.

Line 210 of spot_art_album.sh for example

`curl -X POST -d '{"state":"'"${uri}"'"}' "https://${my_domain}/api/states/sensor.spotify_uri?" -H 'Authorization: Bearer "$HA_Token"'
`
causes an auth error while the below (old format) works 

`curl -X POST -d '{"state":"'"${uri}"'"}' https://${my_domain}/api/states/sensor.spotify_uri? -H "Authorization: Bearer $HA_Token"
`

qry_player_stat.sh appears to have the correct formatting (as well as your domain name hardcoded still @ynot123!) 

Great work on this, it's been working brilliantly for me!

**Comment by ynot123** [comment]
Thanks I will review.  

Missed the qry_player_stat.sh file altogether.  Was a late addition.  My one man quality control team, seems to be letting me down.  

As for the curl error (lines 33 & 35) did you mean too many quotes and / or backticks,.  My {} count seems to be the same in both lines from your email.  It actually works "as-is" on my system (debian) but I will review, it does seem suspect.

I will also test the playlist thing.  Sound's like a contraction issue, I had similar problems with "baby it's cold outside" but may have forgotten to put the logic in for the playlist side :(.

Thanks for taking the time to review and posting the results.  Should see a little change in the next day or so.  I may ask you to test a shell file or two in case your system is somewhat different.  What are running HA or hass.io and on what hardware / os.
Thanks, Ynot.

**Comment by ynot123** [comment]
The shell files have been updated to suit your comments above.  Got lost in the quotes and double quotes, there definitely an error there, though my system didn't complain.  Go figure?

Also removed hard coded domain.  

Will close this issue unless you find it doesn't work on your system.  Thanks, Ynot.

**Comment by jollybully** [comment]
great thanks @ynot123 - running official HA docker image inside of Unraid. 

Thanks for the great work!
